import { useState } from 'react'

const initial = { overall_qual: 7, gr_liv_area: 1800, garage_cars: 2, garage_area: 500, total_bsmt_sf: 900, first_flr_sf: 1000, second_flr_sf: 800, full_bath: 2, bedroom_abv_gr: 3, tot_rms_abv_grd: 7, year_built: 2005, year_remod_add: 2010, lot_area: 9000, neighborhood: 'NAmes', kitchen_qual: 'Gd', exter_qual: 'Gd', bsmt_qual: 'Gd', garage_type: 'Attchd', heating: 'GasA', central_air: 'Y' }
const fields = [['overall_qual', 'Overall quality (1-10)', 'number', 1, 10], ['gr_liv_area', 'Living area (sq ft)', 'number', 0], ['garage_cars', 'Garage capacity (cars)', 'number', 0], ['garage_area', 'Garage area (sq ft)', 'number', 0], ['total_bsmt_sf', 'Basement area (sq ft)', 'number', 0], ['first_flr_sf', 'First-floor area (sq ft)', 'number', 1], ['second_flr_sf', 'Second-floor area (sq ft)', 'number', 0], ['full_bath', 'Full bathrooms', 'number', 0], ['bedroom_abv_gr', 'Bedrooms above grade', 'number', 0], ['tot_rms_abv_grd', 'Total rooms', 'number', 1], ['year_built', 'Year built', 'number', 1800, 2026], ['year_remod_add', 'Year remodeled', 'number', 1800, 2026], ['lot_area', 'Lot area (sq ft)', 'number', 1]]
const selects = [['neighborhood', 'Location / neighborhood', ['NAmes', 'CollgCr', 'OldTown', 'Edwards', 'Somerst', 'Gilbert', 'NridgHt', 'Sawyer', 'NWAmes']], ['kitchen_qual', 'Kitchen finish quality', ['Ex', 'Gd', 'TA', 'Fa', 'Po']], ['exter_qual', 'Exterior finish quality', ['Ex', 'Gd', 'TA', 'Fa', 'Po']], ['bsmt_qual', 'Basement finish quality', ['Ex', 'Gd', 'TA', 'Fa', 'Po', 'None']], ['garage_type', 'Garage arrangement', ['Attchd', 'Detchd', 'BuiltIn', 'CarPort', 'Basment', '2Types', 'None']], ['heating', 'Heating system', ['GasA', 'GasW', 'Grav', 'Wall', 'OthW', 'Floor']], ['central_air', 'Central air conditioning', ['Y', 'N']]]
const optionLabels = { Ex: 'Excellent', Gd: 'Good', TA: 'Typical / average', Fa: 'Fair', Po: 'Poor', None: 'None', Attchd: 'Attached garage', Detchd: 'Detached garage', BuiltIn: 'Built-in garage', CarPort: 'Carport', Basment: 'Basement garage', '2Types': 'More than one type', GasA: 'Gas forced air', GasW: 'Gas hot water', Grav: 'Gravity furnace', Wall: 'Wall furnace', OthW: 'Other hot water', Floor: 'Floor furnace', Y: 'Yes', N: 'No', NAmes: 'North Ames', CollgCr: 'College Creek', OldTown: 'Old Town', Edwards: 'Edwards', Somerst: 'Somerset', Gilbert: 'Gilbert', NridgHt: 'Northridge Heights', Sawyer: 'Sawyer', NWAmes: 'Northwest Ames' }

export default function HouseForm({ onSubmit, loading }) {
  const [form, setForm] = useState(initial)
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  return <form className="house-form" onSubmit={(event) => { event.preventDefault(); onSubmit(form) }}>
    <div className="form-section"><div className="section-heading"><span>01</span><div><h3>Property profile</h3><p>Size, rooms and construction details</p></div></div><div className="field-grid">{fields.map(([key, label, type, min, max]) => <label key={key}>{label}<input required type={type} value={form[key]} min={min} max={max} onChange={(event) => update(key, Number(event.target.value))} /></label>)}</div></div>
    <div className="form-section"><div className="section-heading"><span>02</span><div><h3>Property character</h3><p>Location, finishes, garage and home systems</p></div></div><div className="field-grid">{selects.map(([key, label, options]) => <label key={key}>{label}<select value={form[key]} onChange={(event) => update(key, event.target.value)}>{options.map((option) => <option key={option} value={option}>{optionLabels[option] || option}</option>)}</select></label>)}</div></div>
    <button className="primary-button" type="submit" disabled={loading}>{loading ? <><span className="spinner" />Calculating...</> : 'Predict house price'}<span>↗</span></button>
  </form>
}
