import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

export default function ModelComparison({ metrics, history = [] }) {
  if (!metrics?.models) return <div className="empty-state">Train the models to generate the comparison dashboard.</div>
  const rows = Object.entries(metrics.models).map(([model, values]) => ({ model: model === 'linear_regression' ? 'Linear' : model === 'random_forest' ? 'Forest' : 'ANN', mae: values.mae, rmse: values.rmse, r2: values.r2, training: values.training_time_seconds, prediction: values.prediction_time_seconds }))
  const latest = history[0]
  const latestRows = latest ? Object.entries(latest.predictions).map(([model, value]) => ({ model: model === 'linear_regression' ? 'Linear' : model === 'random_forest' ? 'Forest' : 'ANN', price: value })) : []
  return <div className="chart-grid"><div className="chart-panel"><div className="panel-title"><div><span className="eyebrow">Error profile</span><h3>MAE vs RMSE</h3></div></div><ResponsiveContainer width="100%" height={260}><BarChart data={rows}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="model" /><YAxis /><Tooltip /><Legend /><Bar dataKey="mae" name="MAE" fill="#e27648" radius={[4,4,0,0]} /><Bar dataKey="rmse" name="RMSE" fill="#2a9d8f" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer></div><div className="chart-panel"><div className="panel-title"><div><span className="eyebrow">Goodness of fit</span><h3>R² comparison</h3></div></div><ResponsiveContainer width="100%" height={260}><BarChart data={rows}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="model" /><YAxis domain={[0, 1]} /><Tooltip /><Bar dataKey="r2" name="R²" fill="#274c5e" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer></div>{latestRows.length > 0 && <div className="chart-panel"><div className="panel-title"><div><span className="eyebrow">History-linked result</span><h3>Latest prediction comparison</h3><p className="panel-caption">Updates when you create a new prediction.</p></div></div><ResponsiveContainer width="100%" height={260}><BarChart data={latestRows}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="model" /><YAxis tickFormatter={(value) => `$${Math.round(value / 100000)}L`} /><Tooltip formatter={(value) => [`$${Number(value).toLocaleString('en-US', { maximumFractionDigits: 0 })}`, 'Predicted price']} /><Bar dataKey="price" name="Predicted price" fill="#2563eb" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer></div>}</div>
}
