import { useEffect, useState } from 'react'
import ModelComparison from '../components/ModelComparison'
import MetricsChart from '../components/MetricsChart'
import PredictionActivity from '../components/PredictionActivity'
import { fetchHistory } from '../services/api'

export default function Models({ metrics }) {
  const [history, setHistory] = useState([])
  useEffect(() => { fetchHistory().then(({ data }) => setHistory(data)).catch(() => setHistory([])) }, [])
  const labels = { linear_regression: 'Linear Regression', random_forest: 'Random Forest', neural_network: 'Neural Network' }
  return <><header className="page-header"><div><span className="eyebrow">Evaluation lab</span><h1>ML vs deep learning</h1><p>Compare the same property data across three model families.</p></div></header>{metrics?.models && <section className="surface metrics-table-panel"><div className="panel-heading"><div><span className="eyebrow">Measured performance</span><h3>Model comparison</h3><p className="panel-caption">For prediction accuracy, choose the model with the lowest MAE and RMSE and the highest R². Training and inference show speed, not accuracy.</p></div></div><div className="table-scroll"><table className="metrics-table"><thead><tr><th>Model</th><th>Type</th><th title="Mean Absolute Error: average prediction error in dollars. Lower is better.">MAE ↓</th><th title="Root Mean Squared Error: penalizes larger errors more heavily. Lower is better.">RMSE ↓</th><th title="R-squared: how much of the price variation the model explains. Higher is better, up to 1.0.">R² ↑</th><th title="Time needed to train the model.">Training</th><th title="Time needed to predict one house.">Inference</th></tr></thead><tbody>{Object.entries(metrics.models).map(([key, value]) => <tr key={key}><td><strong>{labels[key]}</strong></td><td><span className="type-pill">{key === 'neural_network' ? 'Deep learning' : 'Machine learning'}</span></td><td>{value.mae.toLocaleString('en-IN', { maximumFractionDigits: 0 })}</td><td>{value.rmse.toLocaleString('en-IN', { maximumFractionDigits: 0 })}</td><td>{value.r2.toFixed(3)}</td><td>{value.training_time_seconds.toFixed(2)}s</td><td>{value.prediction_time_seconds.toFixed(4)}s</td></tr>)}</tbody></table></div></section>}<ModelComparison metrics={metrics} history={history} /><MetricsChart metrics={metrics} /><PredictionActivity history={history} /><div className="method-grid"><div><span>01</span><h3>Linear Regression</h3><p>A transparent statistical baseline that models a linear relationship between the selected features and sale price.</p></div><div><span>02</span><h3>Random Forest</h3><p>An ensemble of decision trees that captures nonlinear interactions and reports model-derived importance.</p></div><div><span>03</span><h3>Neural Network</h3><p>A feed-forward ANN with dense nonlinear layers, dropout, Adam optimization and early stopping.</p></div></div></>
}
